// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcho876BAspPQNOq70jB5xKi4a0kzvFRU',
    appId: '1:908382465371:web:85db78b8086d3861293e7e',
    messagingSenderId: '908382465371',
    projectId: 'porcicultura-95ebb',
    authDomain: 'porcicultura-95ebb.firebaseapp.com',
    storageBucket: 'porcicultura-95ebb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAm5vUrJCTySLMXTiwHzCAj81wOKowB9w',
    appId: '1:908382465371:android:64bb8e0865b1379c293e7e',
    messagingSenderId: '908382465371',
    projectId: 'porcicultura-95ebb',
    storageBucket: 'porcicultura-95ebb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc3tqDMQ0hqhtwWQHtvG7lzzwvcTBCQ5U',
    appId: '1:908382465371:ios:7019160123c26865293e7e',
    messagingSenderId: '908382465371',
    projectId: 'porcicultura-95ebb',
    storageBucket: 'porcicultura-95ebb.appspot.com',
    iosBundleId: 'com.example.porciculturaV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc3tqDMQ0hqhtwWQHtvG7lzzwvcTBCQ5U',
    appId: '1:908382465371:ios:5ea10035d23dac66293e7e',
    messagingSenderId: '908382465371',
    projectId: 'porcicultura-95ebb',
    storageBucket: 'porcicultura-95ebb.appspot.com',
    iosBundleId: 'com.example.porciculturaV3.RunnerTests',
  );
}
